#!/usr/bin/env bash
#
# AlgoPro Engine — one-shot VPS provisioning script (Ubuntu 22.04 / 24.04).
#
# Run as root on a FRESH VPS:
#   curl -fsSL ... or scp this repo up, then:
#   sudo bash deploy/setup.sh algopro.example.com
#
# What it does:
#   1. installs system deps (python venv, nginx, certbot, ufw)
#   2. creates the 'algopro' service user
#   3. copies the app to /opt/algopro and builds the venv
#   4. generates a .env with fresh secrets (you fill in Binance/auth after)
#   5. installs the systemd unit + nginx site
#   6. configures the firewall and provisions TLS via certbot
#
# It is idempotent enough to re-run, but review the .env step — it will NOT
# overwrite an existing .env.

set -euo pipefail

DOMAIN="${1:-}"
if [[ -z "$DOMAIN" ]]; then
    echo "Usage: sudo bash deploy/setup.sh <your-domain>" >&2
    exit 1
fi

APP_USER="algopro"
APP_HOME="/opt/algopro"
APP_DIR="$APP_HOME/algotrade-pro"
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "==> Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
# requirements.txt is pinned to versions with prebuilt cp314 wheels, so the
# system Python on Ubuntu 26.04 (3.14) is used directly — no PPA, no uv.
apt-get install -y python3 python3-venv python3-pip nginx certbot python3-certbot-nginx ufw rsync

echo "==> Creating service user '$APP_USER'"
if ! id "$APP_USER" &>/dev/null; then
    useradd --system --create-home --home-dir "$APP_HOME" --shell /usr/sbin/nologin "$APP_USER"
fi

echo "==> Copying app to $APP_DIR"
mkdir -p "$APP_DIR"
rsync -a --delete \
    --exclude '.git' --exclude 'venv' --exclude '__pycache__' \
    --exclude '*.db' --exclude '*.db-wal' --exclude '*.db-journal' \
    --exclude '.env' --exclude '.pytest_cache' \
    "$SRC_DIR"/ "$APP_DIR"/

echo "==> Building virtualenv (system Python 3.14)"
rm -rf "$APP_DIR/venv"
python3 -m venv "$APP_DIR/venv"
"$APP_DIR/venv/bin/pip" install --upgrade pip
"$APP_DIR/venv/bin/pip" install -r "$APP_DIR/requirements.txt"

# Sanity check: confirm the venv built and uvicorn landed.
"$APP_DIR/venv/bin/python" --version
test -x "$APP_DIR/venv/bin/uvicorn" || { echo "FATAL: uvicorn not installed in venv" >&2; exit 1; }

echo "==> Generating .env (if absent)"
if [[ ! -f "$APP_DIR/.env" ]]; then
    ENC_KEY="$("$APP_DIR/venv/bin/python" -c 'import secrets; print(secrets.token_urlsafe(32))')"
    SESS_KEY="$("$APP_DIR/venv/bin/python" -c 'import secrets; print(secrets.token_urlsafe(32))')"
    HOOK_KEY="$("$APP_DIR/venv/bin/python" -c 'import secrets; print(secrets.token_urlsafe(24))')"
    cat > "$APP_DIR/.env" <<EOF
# ── Generated by deploy/setup.sh — fill in the TODO values, then restart ──
TESTNET_MODE=false
DEBUG=false
HOST=127.0.0.1
PORT=8000

# Secrets generated for this host. Do NOT change ENCRYPTION_KEY after adding
# accounts — stored API secrets become undecryptable.
ENCRYPTION_KEY=$ENC_KEY
SESSION_SECRET=$SESS_KEY
WEBHOOK_SECRET=$HOOK_KEY

# TODO: set your dashboard login.
AUTH_USERNAME=
AUTH_PASSWORD=

REDIS_URL=redis://localhost:6379/0
EOF
    chmod 600 "$APP_DIR/.env"
    echo "    -> wrote $APP_DIR/.env  (set AUTH_USERNAME / AUTH_PASSWORD before starting)"
    echo "    -> WEBHOOK_SECRET = $HOOK_KEY"
else
    echo "    -> .env already exists, leaving untouched"
fi

echo "==> Fixing ownership"
chown -R "$APP_USER:$APP_USER" "$APP_HOME"

echo "==> Installing systemd unit"
cp "$APP_DIR/deploy/algopro.service" /etc/systemd/system/algopro.service
systemctl daemon-reload
systemctl enable algopro

echo "==> Installing nginx site for $DOMAIN"
sed "s/algopro.example.com/$DOMAIN/g" "$APP_DIR/deploy/nginx-algopro.conf" \
    > /etc/nginx/sites-available/algopro.conf
ln -sf /etc/nginx/sites-available/algopro.conf /etc/nginx/sites-enabled/algopro.conf
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

echo "==> Configuring firewall"
ufw allow OpenSSH
ufw allow 'Nginx Full'
ufw --force enable

echo "==> Provisioning TLS certificate"
certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos \
    --register-unsafely-without-email --redirect || \
    echo "    !! certbot failed — check DNS points to this server, then re-run: certbot --nginx -d $DOMAIN"

echo "==> Starting AlgoPro"
systemctl restart algopro

cat <<DONE

────────────────────────────────────────────────────────────────
Setup complete.

Next steps:
  1. Edit $APP_DIR/.env  → set AUTH_USERNAME and AUTH_PASSWORD
  2. sudo systemctl restart algopro
  3. Visit https://$DOMAIN/  and log in
  4. TradingView webhook URL: https://$DOMAIN/api/webhook
       header: X-Webhook-Secret  (value is in .env -> WEBHOOK_SECRET)
  5. In Binance, restrict your API key to this server's IP.

Logs:    journalctl -u algopro -f
Health:  curl -s https://$DOMAIN/api/health
────────────────────────────────────────────────────────────────
DONE
